download_data:
  https://www.arcgis.com/sharing/rest/content/items/db25442a233c44f3a540b26e8a261a55/data: data/NOISE.zip
  https://www.arcgis.com/sharing/rest/content/items/00bdd8df520e478e9505eb656c1780dd/data: data/PARKS.zip
  https://www.arcgis.com/sharing/rest/content/items/b1caf514714645698c1210f29f36be9a/data: data/DISTRICTS.zip
  https://www.arcgis.com/sharing/rest/content/items/fb1550a2e8be4693a18bfd70f9548a2a/data: data/TRANSPORT_LINES.zip
  https://www.arcgis.com/sharing/rest/content/items/5ab5614fae0440ac9cd5dcb0b088d574/data: data/ROADS.zip
  https://raw.githubusercontent.com/kraina-ai/srai-tutorial/sotm2024/data/cadastral_data.geojson: data/DEMOGRAPHY.geojson
